Enforce that `cabal check` is happy
I noticed that the newer version of `cabal check` that we have now has a
`--ignore` option, which lets us use ignore the warnings about missing
dependency bounds and the `werror` flag, I included justification inline.

We had the following errors which I did address:

```
Error: [git-protocol] Cloning over git:// might lead to an arbitrary code
execution vulnerability. Furthermore, popular forges like GitHub do not
support it. Use https:// or ssh:// instead.
These warnings will likely cause trouble when distributing the package:
Warning: [no-maintainer] No 'maintainer' field.
These warnings may cause trouble when distributing the package:
Warning: [doc-place] Please consider moving the file 'CHANGELOG.md' from the
'extra-source-files' section of the .cabal file to the section
'extra-doc-files'.
Error: Hackage would reject this package.
```

I added this check to ci, so we won't regress in the future.